matrix:
  include:
    - language: python
      virtualenv:
        system_site_packages: true
      python: 2.7
      before_install:
        - bash ./creds.sh
      install:
        - pip install -r requirements.txt

      script:
        - cd $TRAVIS_BUILD_DIR/src/backend
        - python manage.py makemigrations --check --dry-run --settings=conf.test || echo "Missing migrations."
        - python manage.py test --settings=conf.test
        - flake8
      after_success:
        - zappa update dev
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash $TRAVIS_BUILD_DIR/deploy.sh
          on:
            branch: master
    - language: node_js
      node_js: 8
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/src/frontend/node_modules

      install:
        - cd $TRAVIS_BUILD_DIR/src/frontend
        - yarn install
      script:
        - npm run build
