matrix:
  include:
    - language: python
      virtualenv:
        system_site_packages: true
      python: 2.7

      install:
        - pip install -r requirements.txt

      script:
        - python ./src/backend/manage.py makemigrations --check --dry-run --settings=conf.test || echo "Missing migrations."
        - python ./src/backend/manage.py test --settings=conf.test
        - flake8
    - language: node_js
      node_js: 8
      cache:
        directories:
          - ./src/frontend/node_modules

      install:
        - cd ./src/frontend
        - yarn install
      script:
        - npm run build
