matrix:
  include:
    - language: python
      virtualenv:
        system_site_packages: true
      python: 2.7
      before_install:
        - ./ecr_credentials.sh
      install:
        - pip install -r requirements.txt

      script:
        - cd $TRAVIS_BUILD_DIR/src/backend
        - python manage.py makemigrations --check --dry-run --settings=conf.test || echo "Missing migrations."
        - python manage.py test --settings=conf.test
        - flake8
      deploy:
      - provider: script
        skip_cleanup: true
        script:
          - cd $TRAVIS_BUILD_DIR/src/backend
          - zappa update dev
          - zappa manage dev "collectstatic --noinput --settings=conf.staging"
        on:
          branch: master
    - language: node_js
      node_js: 8
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/src/frontend/node_modules

      install:
        - cd $TRAVIS_BUILD_DIR/src/frontend
        - yarn install
      script:
        - npm run build
