language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - python ./src/backend/manage.py makemigrations --check --dry-run --settings=conf.test || echo "Missing migrations."
  - flake8
