# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('is_required', models.BooleanField()),
                ('field_type', models.CharField(choices=[(b'text', b'Text'), (b'number', b'Number'), (b'date', b'Date'), (b'enum', b'Enum')], max_length=10)),
                ('enum_values', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.ManyToManyField(to='api.DataField')),
            ],
        ),
        migrations.CreateModel(
            name='RiskValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(null=True)),
                ('number_value', models.BigIntegerField(null=True)),
                ('date_value', models.DateTimeField(null=True)),
                ('enum_value', models.TextField(null=True)),
                ('data_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DataField')),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RiskType')),
            ],
        ),
    ]
