# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='enum_values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
